""" end 09-28-2026 pg268 """

""" start 09-30-2026  """

"""  
Reasoning performance can also be improves through distillation.

- Smaller model (student) is trained on the reasoning traces and answers generated by
    a larger (teacher) model
Distillation is important because the strongest reasoning models are often too
large and expensive to work with directly.

- In what follows, we'll use a stronger teacher to generate reasoning traces
 and then train a smaller student model to reproduce them
- Distillation can be more effective than training a small model using reinforcement learning
    with verifiable rewards. 
    - Hard Distillation - the student is trained on the text generated by the teacher
        Teachers tokesn are treates as the targets - Essentially supervised fine-tuning on synthetic data
        Advantage is that we only need access to teachers generated text, not its logits
        Loss: L = CrossEntropy(y_teacher_tokens, y_student)
    - Soft Distillation - Student is trained to match the teacher's probability distribution
        over the vocabulary by minimizing the KL divergence - train on the logits of the teacher
        L = KL(p_teacher || p_student)
    - Knowledge Distillation - Train studet on the teacher's actual output tokens while also encouraging
        the student to match the teachers full distribution
    Appropriately designed objectives for soft distillation can outperform hard distillation (https://arxiv.org/abs/2306.08543)

Our focus will be on hard distillation because of its practival advantages - 
    - We do not need to know the logits of the teacher,
    - We do not need the tokenizer of the teacher
    - much more expensive to store and use the full token distribution for long reasoning traces

Generating a dataset for reasoning distillation:
 - Student will be the Qwen3 0.6B base model
 - DeepSeek-R1 will be the teacher model. 
We'll feed the MATH-500 evaluation set into the teacher model and collect it's responses as training targets

In distillation, we do not compare the student's reponse to a reference answer, we compare the student's generated
tokens with the teacher's generated tokens (see loss calculation above)

Generating the teacher's responses is time and resource expensive. Here, we'll load the pregenerated dataset.
However, we should review the process as discussed in detail:
https://github.com/rasbt/reasoning-from-scratch/tree/main/ch08/02_generate_distillation_data

"""
import json
import requests
import time
import random
import torch
from pathlib import Path
from pprint import pprint
from reasoning_from_scratch.ch02 import get_device
from reasoning_from_scratch.ch03 import (
    load_model_and_tokenizer,
    render_prompt
)
from reasoning_from_scratch.ch06 import sequence_logprob
from reasoning_from_scratch.ch07 import download_from_github
from reasoning_from_scratch.qwen3 import (
    download_qwen3_small,
    Qwen3Tokenizer
)
"""  
(8.1) Loading Distilled MATH training split
"""
def load_distill_data(local_path=None, partition="deepseek-r1-math-train", save_copy=True):
    if local_path is None:
        local_path = f"{partition}.json"
    local_path = Path(local_path)

    url = (
        "https://huggingface.co/datasets/rasbt/math_distill"
        "/resolve/main/data/"
        f"{partition}.json"
    )
    backup_url = (
        "https://f001.backblazeb2.com/file/reasoning-from-scratch/"
        f"MATH/{partition}.json"
    )
    if local_path.exists():
        with local_path.open("r", encoding="utf-8") as f:
            data = json.load(f)

        size_kb = local_path.stat().st_size / 1e3
        print(f"{local_path}: {size_kb:.1f} KB (cached)")
        return data

    assert partition in (
        "deepseek-r1-math-train",
        "deepseek-r1-math500",
        "qwen3-235b-a22b-math-train",
        "qwen3-235b-a22b-math500",
    )

    try:
        r = requests.get(url, timeout=30)
        r.raise_for_status()
    except requests.RequestException:
        print("Using backup URL.")
        r = requests.get(backup_url, timeout=30)
        r.raise_for_status()

    data = r.json()

    if save_copy:
        with local_path.open("w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)

        size_kb = local_path.stat().st_size / 1e3
        print(f"{local_path}: {size_kb:.1f} KB")

    return data

math_train = load_distill_data(partition="deepseek-r1-math-train")
with open("deepseek-r1-math-train.json", 'r', encoding='utf-8') as file:
    math_train = json.load(file)

""" 
print("Dataset size:", len(math_train))
pprint(math_train[4])
 """

""" 
Output:
deepseek-r1-math-train.json: 107538.0 KB
Dataset size: 12000

Reviewing the dataset we see each entry contains four fields
    - problem: the problem
    - gtruth_answer: correct reference answer
    - message_thinking: reasoning trace by the teacher model
    - message_content: final answer following the reasoning trace
For distillation the two most important fields are the message_thinking (reasoning) 
and message_content (final answer)
"""

"""  
(8.2) Formatting teacher responses for distillation
"""
def format_distilled_answer(entry):
    content = str(entry["message_content"]).strip()
    if not content:
        raise ValueError("Missing non-empty 'message_content' field.")
    thinking = str(entry["message_content"]).strip()
    return f"<think>{thinking}</think>\n\n{content}"

#print(format_distilled_answer(math_train[4]))

""" 
To evaluate the accuracy of the DeepSeek-R1 performance we download the evaluate_json.py script using:

_ = download_from_github(
    "ch03/02_math500-verifier-scripts/evaluate_json.py"
)

Then in the terminale we run the code as: 
!uv run evaluate_json.py \
--json_path "deepseek-r1-math-train.json" \
--gtruth_answer gtruth_answer \
--generated_text message_content

in the terminal

Output:
Accuracy: 90.6% (10871/12000)

The following is data processing
- formatting the prompts and answers
- tokenizing them
- Store token IDs and prompt length
(8.3) Loading the Qwen3 reasoning tokenizer (and understand it) - 2c Stage 1
"""
def load_reasoning_tokenizer(local_dir="qwen3"):
    download_qwen3_small(
        kind="reasoning", tokenizer_only=True, out_dir=local_dir
    )
    tokenizer_path = Path(local_dir) / "tokenizer-reasoning.json"
    tokenizer = Qwen3Tokenizer(
        tokenizer_file_path=tokenizer_path,
        apply_chat_template=True,
        add_generation_prompt=True,
        add_thinking=True
    )
    return tokenizer

""" 
tokenizer = load_reasoning_tokenizer()
prompt = "Sam is hired for a 20-day period..."
prompt_ids = tokenizer.encode(prompt)
decoded_prompt = tokenizer.decode(prompt_ids)
print(decoded_prompt)
 """

"""  
Output:
<|im_start|>user
Sam is hired for a 20-day period...<|im_end|>
<|im_start|>assistant

<|im_start|>user - Start token for the user prompts
<|im_end|>  -  Stop token for user prompts
<|im_start|>assistant are the start tokens for the LLM answer

"""




""" end 09-30-2026 pg279 """

""" start 10-01-2026  """


"""
The last generated output is referred to as the chat-style wrapping which is optional, but common convention for instruction
and chat fine-tuning.

For the target answer we'll disable this wrapping by setting chat_wrapped=False
To see the effect consider the following example.
"""
answer = (
    "<think>Okay, let me try to solve "
    "this problem...</think> \\boxed{4}"
)
tokenizer = load_reasoning_tokenizer()

""" 
answer_ids = tokenizer.encode(answer, chat_wrapped=False)
decoded_answer = tokenizer.decode(answer_ids)
print(decoded_answer)

"""

"""
Output:
  <think>Okay, let me try to solve this problem...</think> \boxed{4}
  <|im_start|> & <|im_end|> tags are no longer present
    chat template for the response is suppressed
For training we need the full sequence of token IDs: 
    - The wrapped prompr
    - The teachers answers
    - End-of-sequence token
Using the immediate preceeding examples, the sequence the model will see is:
token_ids = prompt_ids + answer_ids + [tokenizer.eos_token_id]
decoded_token_ids = tokenizer.decode(token_ids)
SO far we've only loaded the tokenizer. We can apply the formatting and tokenization steps to the whole dataset
(2c Stage 2 - tokenize the dataset)
(8.4) Building and inspecting tokenized distillation examples
"""
def build_examples(data, tokenizer):
    examples = []
    skipped = 0
    for entry in data:
        try:
            """ Step 1: Render problem in the chat format """
            prompt = render_prompt(entry["problem"])
            prompt_ids = tokenizer.encode(prompt)
            """ Step 2: tokenize the teachers reasoning trace and final answer """
            target_answer = format_distilled_answer(entry)
            answer_ids = tokenizer.encode(
                target_answer, chat_wrapped=False
            )
            """ Step 3: Combine prompt and answer for training """
            token_ids = (prompt_ids + answer_ids + [tokenizer.eos_token_id])
            if len(token_ids) < 2:
                skipped += 1
                continue
            examples.append({
                "token_ids": token_ids,
                "prompt_len": len(prompt_ids)
            })
        except (KeyError, TypeError, ValueError):
            skipped += 1
    return examples, skipped


examples, skipped = build_examples(math_train, tokenizer)

""" 
print("Number of examples:", len(examples))
print("Number of skipped examples:", skipped)
print(tokenizer.decode(examples[4]["token_ids"]))

 """

"""  
Output:
Number of examples: 12000
Number of skipped examples: 0
Answer:<|im_end|>
<|im_start|>assistant
<think>Sam worked \\( x \\) days and did not work \\( y \\) days. We know:
\\[
    .....
Sam did not work \\(\\boxed{6}\\) days.<|im_end|>

The above output used the chat template, answer reasoning trace is enclosed in 
<think></think> tags, and ends with <|im_end|>

We want to examine the sequence lengths. Tells us the average length of the samples and which are outliers.
We could also decide to remove examples above a chosen maximum length
(8.5) Computing lenghts and filtering long examples
"""
def compute_length(examples, answer_only=False):
    lengths = []
    for ex in examples:
        total = len(ex["token_ids"])
        length = total - ex["prompt_len"] if answer_only else total
        lengths.append(length)

    avg_len = round(sum(lengths) / len(lengths))
    shortest_len = min(lengths)
    longest_len = max(lengths)
    shortest_idx = lengths.index(shortest_len)
    longest_idx = lengths.index(longest_len)
    print(f"Average: {avg_len} tokens")
    print(f"Shortest: {shortest_len} tokens (index {shortest_idx})")
    print(f"Longest: {longest_len} tokens (index {longest_idx})")

compute_length(examples)

"""  
Output:
Average: 800 tokens
Shortest: 63 tokens (index 7409)
Longest: 42005 tokens (index 2529)
Note: our output is differs from what is reported in the literature
Average: 2946 tokens
Shortest: 236 tokens (index 10846)
Longest is correct.
(8.6) Filtering long examples
"""
def filter_examples_by_max_len(examples, max_len=2048):
    filtered_examples = [
        s for s in examples
        if len(s["token_ids"]) <= max_len
    ]
    print("Original:", len(examples))
    print("Filtered:", len(filtered_examples))
    print("Removed:", len(examples) - len(filtered_examples))
    return filtered_examples

filtered_examples = filter_examples_by_max_len(examples, max_len=412)

rng = random.Random(123)
rng.shuffle(filtered_examples)

train_examples = filtered_examples[25:]
val_examples = filtered_examples[:25]


""" 
print("Number of train examples:", len(train_examples))
print("Number of validation examples:", len(val_examples))
"""

"""  
(8.8) Note that below we ignore the base tokenizer since we want to use the tokenizer with the
<think></think> tags

"""

device = get_device()

model, _ = load_model_and_tokenizer(
    which_model="base",
    device=device,
    use_compile=False
)

"""  
Now we want to implement the cross_entropy loss that will serve as the training signal during distillation
when we implement the training loop later
Here, the target class we want to predict at each position is the next token in the teacher-generated sequence
We connect the cross-entropy loss directly to the log-probability computations from Ch5 and Ch6
Log-probability measures how much probability the model assigns to the correct next token,
    - higher log probability means the model is more confident in the correct token
    - Lower log-probability means the opposite
cross-entropy is the negative average of the token log probabilities

(8.9) Computing average negative log probabilities
"""

# 5730 is the shortest example in train_examples
""" 
token_ids = train_examples[5730]["token_ids"]
prompt_len = train_examples[5730]["prompt_len"]

tok = torch.tensor(token_ids, dtype=torch.long, device=device)
with torch.no_grad():
    seq_logprob = sequence_logprob(model, tok, prompt_len)
    num_answer_tokens = tok.numel() - prompt_len
    avg_logprob = -seq_logprob / num_answer_tokens
print(f"Average logprob: {avg_logprob:.2f}")
 """

"""  
(8.10) Computing cross-entropy loss directly
"""
""" 
input_ids = tok[:-1].unsqueeze(0)
target_ids = tok[1:]  # Targets are inputs shifted by one position
logits = model(input_ids).squeeze(0)
# Remove prompt tokens
first_answer_logit_idx = max(prompt_len - 1, 0)
answer_logits = logits[first_answer_logit_idx:]
answer_targets = target_ids[first_answer_logit_idx:]
with torch.no_grad():
    ce_mean_direct = torch.nn.functional.cross_entropy(
        answer_logits, answer_targets
    )
print(f"Cross-entropy: {ce_mean_direct:.2f}")

 """
""" end 10-06-2026 pg289 """

""" start 10-06-2026  """

"""
Output:
Our results from cross-entropy does not match the literature.
The data set is somehow different. We'll continue to explore as we
proceed
(8.11) Defining the loss for one distillation example - wraps the logic above in 
a helper function  

See Appendix E for batching and throughput-oriented execution
"""
def compute_example_loss(model, example, device):
    token_ids = example["token_ids"]
    prompt_len = example["prompt_len"]
    """ Create input-target pairs that are shifted by one token """
    input_ids = torch.tensor(
        token_ids[:-1], dtype=torch.long, device=device
    ).unsqueeze(0)
    target_ids = torch.tensor(
        token_ids[1:], dtype=torch.long, device=device
    )
    """ Get model logits for the token ids """
    logits = model(input_ids).squeeze(0)
    """ Ignore prompt tokens so that computed loss is on the distilled answer only """
    answer_start = max(prompt_len - 1, 0)
    answer_logits = logits[answer_start:]
    answer_targets = target_ids[answer_start:]
    """ compute cross-entropy loss """
    loss = torch.nn.functional.cross_entropy(
        answer_logits, answer_targets
    )
    return loss

""" 
with torch.no_grad():
    loss = compute_example_loss(
        model, train_examples[5730], device
    )
print(f"Loss: {loss:.2f}")

 """

"""  
Output
Average logprob: 0.25
Cross-entropy: 0.25
Loss: 0.25
All three (3) examples produce the same cross-entropy loss value of 0.25
No we define a wrapper function to iteratively compute the average loss across multiple examples
(8.12) Evaluating loss across multiple examples
"""
def evaluate_examples(model, examples, device):
    was_training = model.training
    """ Switch temporarily to evaluation mode to score the examples """
    model.eval()
    total_loss = 0.0
    num_examples = 0

    """ Sum the loss over the examples """
    for example in examples:
        loss = compute_example_loss(model, example, device)
        total_loss += loss.item()
        num_examples += 1
    """ Restore training mode so helper is safe to call during training """
    if was_training:
        model.train()
    """ return the average loss over all examples """
    return total_loss / num_examples

""" 
train_loss = evaluate_examples(model, train_examples[:3], device)
print(f"Train loss (3 examples): {train_loss:.2f}")
val_loss = evaluate_examples(model, val_examples[:3], device)
print(f"Validation loss (3 examples): {val_loss:.2f}")
 """

"""  
Output:
Train loss (3 examples): 0.30 (actual in literature: 0.98)
Validation loss (3 examples): 0.25 (actual in literature: 1.02)

Implementing the Training Loop
The training loop we'll use is similar to the GRPO loop in Chapter 6. Main difference is here we revisit the same
training set multiple times across epochs and optimize the cross-entropy distillation loss
1 - initialize the pretrained model and optimizer
2 - for each epoch
    3 - shuffle the dataset
        4 - for each training step
            5 - reset loss gradient from previous step
            6 - calculate the cross-entropy loss
            7 - backward pass to calculate the loss gradient
            8 - update model weights using the loss gradient
            9 - Calculate validation loss and report metris
        10 - save a model checkpoint (optional step for tracking and saving the training progress)
4 - 8 are identical to the training loop in chapter 6
(8.13) Implementing the distillation training loop
    We create the following functions
        train_distillation, save_checkpoint, append_csv_metrics
"""
def train_distillation(
    model,
    train_examples,
    val_examples,
    device,
    epochs=2,
    lr=5e-6,
    grad_clip_norm=None,
    seed=123,
    log_every=50,
    checkpoint_dir="checkpoints",
    csv_log_path=None,
):
    """ Step 1: Initializa the optimizer (model is already loaded) """
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    model.train()
    total_steps = epochs * len(train_examples)
    global_step = 0
    rng = random.Random(seed)

    if csv_log_path is None:
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        csv_log_path = f"train_distill_metrics_{timestamp}.csv"
    csv_log_path = Path(csv_log_path)

    """ Step 2: Iterate over the training epochs """
    for epoch in range(1, epochs + 1):
        epoch_examples = list(train_examples)
        """ Step 3: Shuffle the training examples at the start of the epoch """
        rng.shuffle(epoch_examples)
        """ Step 4: Iterate over the training examples in the epoch """
        for example in epoch_examples:
            global_step += 1
            """ Step 5: Reset loss gradient """
            optimizer.zero_grad()
            """ Step 6: Compute the cross entropy loss for the current example """
            loss = compute_example_loss(model, example, device)
            """ Step 7: Backpropagate gradients """
            loss.backward()
            """ Optionally clip large gradients to improve training stability """
            if grad_clip_norm is not None:
                torch.nn.utils.clip_grad_norm_(
                    model.parameters(), grad_clip_norm
                )
            """ Step 8: Update the model weights """
            optimizer.step()
            """ Step 9: Periodically evaluate the current model on the validation set """
            if log_every and global_step % log_every == 0:
                val_loss = evaluate_examples(
                    model=model,
                    examples=val_examples,
                    device=device
                )
                model.train()
                print(
                    f"[Epoch {epoch}/{epochs} "
                    f"Step {global_step}/{total_steps}] "
                    f"train_loss={loss.item():.4f} "
                    f"val_loss={val_loss:.4f}"
                )
                append_csv_metrics(
                    csv_log_path=csv_log_path,
                    epoch_idx=epoch,
                    total_steps=global_step,
                    train_loss=loss.item(),
                    val_loss=val_loss,
                )
        ckpt_path = save_checkpoint(
            model=model,
            checkpoint_dir=checkpoint_dir,
            step=global_step,
            suffix=f"epoch{epoch}",
        )
        print(f"Saved checkpoint to {ckpt_path}")
    return model

def save_checkpoint(model, checkpoint_dir, step, suffix=""):
    checkpoint_dir = Path(checkpoint_dir)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    suffix = f"-{suffix}" if suffix else ""
    ckpt_path = (
        checkpoint_dir /
        f"qwen3-0.6B-distill-step{step:05d}{suffix}.pth"
    )
    torch.save(model.state_dict(), ckpt_path)
    return ckpt_path


def append_csv_metrics(
    csv_log_path,
    epoch_idx,
    total_steps,
    train_loss,
    val_loss
):
    if not csv_log_path.exists():
        csv_log_path.write_text(
            "epoch,total_steps,train_loss,val_loss\n",
            encoding="utf-8",
        )
    with csv_log_path.open("a", encoding="utf-8") as f:
        f.write(
            f"{epoch_idx},{total_steps},{train_loss:.6f},"
            f"{val_loss:.6f}\n"
        )
        


"""  
Original: 12000
Filtered: 9186
Removed: 2814

That was out original filtered set totaling 9168
That would require too much resources

To arrive at an filtered set as
Original: 12000
Filtered: 2450
Removed: 9550
We set max_len=412 on line 344

We train on only a tiny subset - first ten (10) examples and 10 validations examples
We only tring for 2 epochs. Learning rate of 5e-6 is in a reasonable range for fine-tuning
a pre-trained model.
log_every=5 means that validation loss is measured every 5 training steps

Below is the actual training call which we'll execute at a later date
"""
""" 
torch.manual_seed(0)
train_distillation(
    model,
    train_examples=train_examples[:10],
    val_examples=val_examples[:10],
    device=device,
    epochs=2,
    lr=5e-6,
    grad_clip_norm=1.0,  # Same as in chapter 6
    seed=123,
    log_every=5,
    csv_log_path="train_distill_metrics.csv"
)
"""

import csv
import matplotlib.pyplot as plt

"""  
We will execute the training run later.
For now we down load the training results using

download_from_github(
    "ch08/03_logs/deepseek-r1-2048_distill_metrics.csv"
)

"""

download_from_github(
    "ch08/03_logs/deepseek-r1-2048_distill_metrics.csv"
)


def plot_distill_metrics(csv_path="train_distill_metrics.csv"):
    total_steps, train_losses, val_losses, epoch_bounds = [], [], [], {}

    with open(csv_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            step = int(row["total_steps"])
            epoch = int(row["epoch"])
            total_steps.append(step)
            train_losses.append(float(row["train_loss"]))
            val_losses.append(float(row["val_loss"]))
            epoch_bounds.setdefault(epoch, [step, step])[1] = step  # first/last step for each epoch

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(total_steps, train_losses, label="train_loss", alpha=0.3)
    ax.plot(total_steps, val_losses, label="val_loss")
    ax.set_xlabel("Total Steps")
    ax.set_ylabel("Loss")
    ax.legend()

    # Epoch axis
    epoch_axis = ax.secondary_xaxis("bottom")
    epoch_axis.spines["bottom"].set_position(("outward", 45))
    epochs = sorted(epoch_bounds)
    epoch_axis.set_xticks(
        [(epoch_bounds[epoch][0] + epoch_bounds[epoch][1]) / 2 
          for epoch in epochs]
    )
    epoch_axis.set_xticklabels(epochs)
    epoch_axis.set_xlabel("Epoch")

    plt.tight_layout()
    plt.savefig("distillation_metrics.png") 
    plt.show()


plot_distill_metrics("deepseek-r1-2048_distill_metrics.csv")
""" end 10-06-2026 pg2 """

""" start 10-07-2026  """